FROM java:8

RUN mkdir -p /home/igor/Документы/Docker/SOAP

WORKDIR /home/igor/Документы/Git/andersen/SOAP-service-command/

COPY . /home/igor/Документы/Git/andersen/SOAP-service-command/

CMD ["java", "SoapServer.java"]